apiVersion: v1
kind: ConfigMap
metadata:
  name: demo2-config
data:
  application.properties: |
    app.welcomeMessage={{ .Values.app.welcomeMessage | quote }}
    logging.level.root={{ .Values.logging.level.root | quote }}
    calculation.type={{ .Values.calculation.type | quote }}
